# Generated by Django 3.1 on 2021-05-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
